version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=postgres
      - DB_DATABASE=tugas-akhir
      - DB_USERNAME=postgres
      - DB_PASSWORD=Rashford10
      - DB_CONNECTION=pgsql
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./storage:/var/www/storage

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tugas-akhir
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rashford10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: